# on: 
#   pull_request:
#     branches: [ main ]
# name: ðŸš€ Deploy website
# jobs:
#   web-deploy:
#     name: ðŸŽ‰ Deploy
#     runs-on: ubuntu-latest
#     steps:
#     - name: ðŸšš Get latest code
#       uses: actions/checkout@v2
   
#     - name: Use Node.js 12
#       uses: actions/setup-node@v2-beta
#       with:
#         node-version: '12'
      
#     - name: ðŸ”¨ Build Project
#       run: |
#         npm install
#         npm run build

#     - name: ðŸ“‚ Sync files
#       uses: SamKirkland/FTP-Deploy-Action@4.1.0
#       with:
#         server: ${{ secrets.FTP_SERVER }}
#         username: ${{ secrets.FTP_USERNAME }}
#         password: ${{ secrets.PASSWORD }}
#         exclude:
#           - **/.git*
#           - **/.git*/**
#           - **/node_modules/**
#           - fileToExclude.txt
